version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    container_name: cache
    image: redis:7.2.7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - backend

  app: # <-- aqui estava errado (um espaço a mais antes de "app")
    build: .
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      BASE_URL: http://localhost:3000
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      CACHE_HOST: redis
      CACHE_PORT: 6379
      CACHE_USERNAME:
      CACHE_PASSWORD:
    networks:
      - backend

volumes:
  db-data:
  redis:

networks:
  backend:
