version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    container_name: cache
    image: redis:7.2.7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - backend

volumes:
  db-data:
  redis:

networks:
  backend:
